#
# Copyright (C) 2020-2024 Arm Limited or its affiliates and Contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
name: CI

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ inputs.branch || github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  publish-project-action-test:
    name: Publish Action Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # this repository
      - uses: actions/checkout@v4 # test repository
        with: 
          repository: Arm-Examples/Hello_LPCXpresso55S69
          path: test
      - uses: ./
        name: Import Project Action
        with:
          branch: main
          project-file: ./test/hello.csolution.yml
          dry-run: true
          PUBLISH_API_KEY: ${{ secrets.KEIL_API_TOKEN }}
          CMSIS_API_KEY: ${{ secrets.CMSIS_API_KEY }}
